---
title: "Practice Quiz 5"
author: "Veesta Mavandadi"
date: "November 12, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1: Single Regressions 
#Does conscientiousness contribute to the prediction of job performance beyond GMA?
Conscientiousness accounted for an additional 10% of the variance in job performance ratings beyond GMA alone, sr2=.10, 95% CI[.05,.14]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. However, when considering both predictors together, the total percentage variance accounted for increased to 36%, R2=.36, 95% CI[.29,.41], F(2,497)=137.5, p<.001. As a result, conscientiousness does contribute to the prediction of job performance beyond that of only GMA. 

#Do Assessment Centre ratings contribute to prediction of jp beyond GMA?
Assessment Centre ratings accounted for an additional 2% of the variance in job performance ratings beyond GMA alone, sr2=.02, 95% CI[-.00,.04]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. However, when considering both predictors together, the total percentage variance accounted for increased to 28%, R2=.28, 95% CI[.21,.34], F(2,497)=95.56, p<.001. As a result, assessment centre ratings do contribute to the prediction of job performance beyond that of only GMA. 

#Do Graphology ratings contribute to prediction beyond GMA?
Graphology ratings did not account for any additional variance in job performance ratings beyond GMA alone, sr2=.00, 95% CI[.00,.00]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. Similarily, when considering both predictors together, the total percentage variance accounted remained 26%, R2=.26, 95% CI[.20,.32], F(2,497)=87.54, p=.60. As a result, graphology ratings do not contribute to the prediction of job performance beyond that of only GMA. 

#Which additional predictor would you use? 
Conscientiousness as it contributes an additional 10% to the varaince in job performance ratings beyond GMA alone brining the toal percentage variance accounted for to 36%. 

##Part 2: Answer the Same Questions Using Two-Block Regressions

#Question 1
Conscientiousness accounted for an additional 10% of the variance in job performance ratings beyond GMA alone, $\Delta R2$=.10, 95% CI[.05,.14]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. However, when considering both predictors together, the total percentage variance accounted for increased to 36%, R2=.36, 95% CI[.29,.41], F(2,497)=137.5, p<.001. As a result, conscientiousness does contribute to the prediction of job performance beyond that of only GMA. Using two-block regressions do not change the results of the regression, they are just a different way of finding the same answer. 

#Question 2 
Assessment Centre ratings accounted for an additional 2% of the variance in job performance ratings beyond GMA alone, $\Delta R2$=.02, 95% CI[-.00,.04]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. However, when considering both predictors together, the total percentage variance accounted for increased to 28%, R2=.28, 95% CI[.21,.34], F(2,497)=95.56, p<.001. As a result, assessment centre ratings do contribute to the prediction of job performance beyond that of only GMA. Using two-block regressions do not change the results of the regression, they are just a different way of finding the same answer.

#Question 3
Graphology ratings did not account for any additional variance in job performance ratings beyond GMA alone, $\Delta R2$=.00, 95% CI[.00,.00]. When considering GMA alone, the total variance accounted for was 26%, R2=.26, 95% CI[.20,.32]. Similarily, when considering both predictors together, the total percentage variance accounted remained 26%, R2=.26, 95% CI[.20,.32], F(2,497)=87.54, p=.60. As a result, graphology ratings do not contribute to the prediction of job performance beyond that of only GMA. Using two-block regressions do not change the results of the regression, they are just a different way of finding the same answer.

##Part 3: Confidence and Prediction Intervals

#Using GMA and conscientiousness, what is the confidence interval for predicted performance scores at the mean GMA and mean conscientiousness. 

Mean general mental ability is *M*=100.00, *SD*=15.10, while the mean conscientiousness level is *M*=120.00, *SD*=8.30. Considering these values, the best estimate of the predicted population mean for job performance is *M*=101.00, CI 95%[100.28,101.72]. 

#What is the prediction interval? 

Considering a general mental ability level (GMA) of *M*=100.00 and a mean conscientiousness level of *M*=120.00, the range of of possible predicted predicted job performance values is PI 95%[84.87, 117.13]. This means that individuals with a mean GMA of 100 and a mean conscientiousness level of of 120, could achieve job performance ratings between 84.87 and 117.13 with 95% prediction confidence. 